# Copyright 2022 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ required "A valid webhook.webhookNames.defaulting is required" .Values.webhook.webhookNames.defaulting }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: {{ required "A valid webhook.webhookNames.defaulting is required" .Values.webhook.webhookNames.defaulting }}
    sideEffects: None
    {{- if .Values.webhook.webhookTimeoutSeconds }}
    {{- if .Values.webhook.webhookTimeoutSeconds.defaulting }}
    timeoutSeconds: {{ .Values.webhook.webhookTimeoutSeconds.defaulting }}
    {{- end }}
    {{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ required "A valid webhook.webhookNames.validating is required" .Values.webhook.webhookNames.validating }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: {{ required "A valid webhook.webhookNames.validating is required" .Values.webhook.webhookNames.validating }}
    sideEffects: None
    {{- if .Values.webhook.webhookTimeoutSeconds }}
    {{- if .Values.webhook.webhookTimeoutSeconds.validating }}
    timeoutSeconds: {{ .Values.webhook.webhookTimeoutSeconds.validating }}
    {{- end }}
    {{- end }}