coverage:
  status:
    project:
      default:
        target: auto
        informational: true
    patch:
      default:
        target: 70%
        threshold: 5%

flags:
  unit-tests:
    paths:
      - cmd/
    carryforward: true
  e2e-tests:
    paths:
      - "**/*"
    carryforward: true

flag_management:
  individual_flags:
    - name: unit-tests
      statuses:
        - type: project
          target: auto
        - type: patch
          target: 70%
    - name: e2e-tests
      statuses:
        - type: project
          target: auto
        - type: patch
          target: auto
