apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "policy-controller.fullname" . }}-webhook
  labels:
    {{- include "policy-controller.labels" . | nindent 4 }}
    control-plane: {{ template "policy-controller.fullname" . }}-webhook
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # Allow the reconciliation of exactly our validating webhook.
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["list", "watch"]

  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["get", "update", "delete"]
    resourceNames:
    - {{ required "A valid cosign.webhookName is required" .Values.cosign.webhookName | quote }}
    - {{ required "A valid webhook.webhookNames.defaulting is required" .Values.webhook.webhookNames.defaulting | quote }}
    - {{ required "A valid webhook.webhookNames.validating is required" .Values.webhook.webhookNames.validating | quote }}

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
    # The webhook configured the namespace as the OwnerRef on various cluster-scoped resources,
    # which requires we can Get the system namespace.
    resourceNames: [ "{{ .Release.Namespace }}" ]

  - apiGroups: [""]
    resources: ["namespaces/finalizers"]
    verbs: ["update"]
    resourceNames: [ "{{ .Release.Namespace }}" ]

  # This is needed by k8schain to support fetching pull secrets attached to pod specs
  # or their service accounts.  If pull secrets aren't used, the "secrets" below can
  # be safely dropped, but the logic will fetch the service account to check for pull
  # secrets.
  - apiGroups: [""]
    resources: ["serviceaccounts", "secrets"]
    verbs: ["get"]

  # Allow reconciliation of the ClusterImagePolic CRDs.
  - apiGroups: ["policy.sigstore.dev"]
    resources: ["clusterimagepolicies", "clusterimagepolicies/status"]
    verbs: ["get", "list", "update", "watch", "patch"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "update", "list"]
    resourceNames: ["trustroots.policy.sigstore.dev"]

  - apiGroups: ["policy.sigstore.dev"]
    resources: ["trustroots", "trustroots/status"]
    verbs: ["get", "list", "update", "watch", "patch"]
