apiVersion: v1
kind: Secret
metadata:
  {{- if or .Values.webhook.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.webhook.service.annotations }}
    {{ toYaml .Values.webhook.service.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "policy-controller.labels" . | nindent 4 }}
    control-plane: {{ template "policy-controller.fullname" . }}-webhook
  name: webhook-certs
  namespace: {{ .Release.Namespace }}
# The data is populated at install time.
