apiVersion: v1
data:
  RELATED_IMAGE_OSE_CLI: registry.redhat.io/openshift4/ose-cli@sha256:2bc6e85e12269f8fe42bebcc69587714715bcf69c60a541096a07683cc158fa5
  RELATED_IMAGE_POLICY_CONTROLLER: registry.redhat.io/rhtas/policy-controller-rhel9@sha256:278e56014866f4d878c84eb44cce7e242189f74d4d4197aee27f4919f8ba9fce
kind: ConfigMap
metadata:
  name: policy-op-related-images
