apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2025-05-08T11:56:17Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: policy-controller-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: rhtas-policy-controller
  displayName: rhtas-policy-controller
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  - test1
  links:
  - name: Policy Controller Operator
    url: https://policy-controller-operator.domain
  maintainers:
  - email: japower@redhat.com
    name: Jason Power
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
