apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.policycontrollers.rhtas.charts.redhat.com
webhooks:
  - name: validation.policycontrollers.rhtas.charts.redhat.com
    clientConfig:
      service:
        name: controller-manager-webhook-service
        namespace: system
        path: /validate
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - operations: [ "CREATE" ]
        apiGroups:   [ "rhtas.charts.redhat.com" ]
        apiVersions: [ "v1alpha1" ]
        resources:   [ "policycontrollers" ]
    sideEffects: None
    admissionReviewVersions: [ "v1" ]
    timeoutSeconds: 5
