{{- $pc := index .Subcharts "policy-controller" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: leases-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policy-controller.labels" $pc | nindent 4 }}
    control-plane: {{ template "policy-controller.fullname" $pc }}-webhook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: leases-cleanup
    spec:
      serviceAccountName: {{ template "webhook.serviceAccountName" $pc }}-cleanup
      {{- if $pc.Values.leasescleanup.automountServiceAccountToken }}
      automountServiceAccountToken: true
      {{- else }}
      automountServiceAccountToken: false
      {{- end }}
      containers:
        - name: kubectl
          image: "{{ template "leases-cleanup.image" $pc.Values.leasescleanup.image }}"
          imagePullPolicy: "{{ $pc.Values.leasescleanup.image.pullPolicy }}"
          command:
            - /bin/sh
            - -c
            - >
              kubectl delete leases \
                --field-selector metadata.name!=policy-controller-operator \
                --ignore-not-found \
                -n {{ .Release.Namespace }}
          {{- if $pc.Values.leasescleanup.resources }}
          resources:
            {{- if $pc.Values.leasescleanup.resources.limits }}
            limits:
              {{- if $pc.Values.leasescleanup.resources.limits.cpu }}
              cpu: {{ $pc.Values.leasescleanup.resources.limits.cpu }}
              {{- end }}
              {{- if $pc.Values.leasescleanup.resources.limits.memory }}
              memory: {{ $pc.Values.leasescleanup.resources.limits.memory }}
              {{- end }}
            {{- end }}
            {{- if $pc.Values.leasescleanup.resources.requests }}
            requests:
              {{- if $pc.Values.leasescleanup.resources.requests.cpu }}
              cpu: {{ $pc.Values.leasescleanup.resources.requests.cpu }}
              {{- end }}
              {{- if $pc.Values.leasescleanup.resources.requests.memory }}
              memory: {{ $pc.Values.leasescleanup.resources.requests.memory }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if $pc.Values.leasescleanup.podSecurityContext.enabled }}
          securityContext:
            {{- with $pc.Values.leasescleanup.podSecurityContext }}
            {{- omit . "enabled" | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
      restartPolicy: OnFailure
      {{- if $pc.Values.leasescleanup.priorityClass }}
      priorityClassName: {{ $pc.Values.leasescleanup.priorityClass }}
      {{- end }} 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "policy-controller.fullname" $pc }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policy-controller.labels" $pc | nindent 4 }}
    control-plane: {{ template "policy-controller.fullname" $pc }}-cleanup
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ include "webhook.serviceAccountName" $pc }}-cleanup
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "policy-controller.fullname" $pc }}-cleanup
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "policy-controller.fullname" $pc }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policy-controller.labels" $pc | nindent 4 }}
    control-plane: {{ template "policy-controller.fullname" $pc }}-cleanup
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list","delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "policy-controller.labels" $pc | nindent 4 }}
    control-plane: {{ template "policy-controller.fullname" $pc }}-cleanup
  name: {{ template "webhook.serviceAccountName" $pc }}-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded

# Base: https://github.com/sigstore/helm-charts/blob/main/charts/policy-controller/templates/webhook/cleanup-leases.yaml
