{{- $pc := index .Subcharts "policy-controller" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "policy-controller.fullname" $pc }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policy-controller.labels" $pc | nindent 4 }}
    control-plane: {{ template "policy-controller.fullname" $pc }}-webhook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ include "webhook.serviceAccountName" $pc }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "policy-controller.fullname" $pc }}-webhook
  apiGroup: rbac.authorization.k8s.io

# Base: https://github.com/sigstore/helm-charts/blob/main/charts/policy-controller/templates/webhook/rolebinding_webhook.yaml
