# permissions for end users to view policycontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: policy-controller-operator
    app.kubernetes.io/managed-by: kustomize
  name: policycontroller-viewer-role
rules:
- apiGroups:
  - rhtas.charts.redhat.com
  resources:
  - policycontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rhtas.charts.redhat.com
  resources:
  - policycontrollers/status
  verbs:
  - get
