apiVersion: rhtas.charts.redhat.com/v1alpha1
kind: PolicyController
metadata:
  name: policycontroller-sample
spec:
  # Default values copied from <project_dir>/helm-charts/policy-controller/values.yaml
  commonAnnotations: {}
  commonNodeSelector: {}
  commonTolerations: []
  cosign:
    cosignPub: ""
    webhookName: policy.sigstore.dev
    webhookTimeoutSeconds: {}
  imagePullSecrets: []
  installCRDs: true
  leasescleanup:
    automountServiceAccountToken: true
    image:
      pullPolicy: IfNotPresent
      repository: cgr.dev/chainguard/kubectl
      version: latest-dev
    podSecurityContext:
      enabled: false
    priorityClass: ""
    resources:
      limits:
        cpu: ""
        memory: ""
      requests:
        cpu: ""
        memory: ""
  loglevel: info
  serviceMonitor:
    enabled: false
  webhook:
    affinity: {}
    automountServiceAccountToken: true
    configData: {}
    customLabels: {}
    env: {}
    envFrom: {}
    extraArgs: {}
    failurePolicy: Fail
    name: webhook
    namespaceSelector:
      matchExpressions:
      - key: policy.sigstore.dev/include
        operator: In
        values:
        - "true"
    podAnnotations: {}
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    priorityClass: ""
    registryCaBundle: {}
    replicaCount: 1
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    service:
      annotations: {}
      port: 443
      type: ClusterIP
    serviceAccount:
      annotations: {}
      create: true
      name: ""
    volumeMounts: []
    volumes: []
    webhookNames:
      defaulting: defaulting.clusterimagepolicy.sigstore.dev
      validating: validating.clusterimagepolicy.sigstore.dev
    webhookTimeoutSeconds: {}
  
  
