apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: RELATED_IMAGE_POLICY_CONTROLLER
              value: ""
            - name: RELATED_IMAGE_OSE_CLI
              value: ""
