---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: registries
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/securesign/policy-controller
      source: registry.redhat.io/rhtas/policy-controller-rhel9
    - mirrors:
        - quay.io/securesign/policy-controller-operator
      source: registry.redhat.io/rhtas/policy-controller-rhel9-operator
    - mirrors:
        - quay.io/securesign/policy-controller-operator-bundle
      source: registry.redhat.io/rhtas/policy-controller-operator-bundle
