apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/policy-controller-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
      && (".tekton/policy-controller-operator-bundle-push.yaml".pathChanged() || ".tekton/policy-controller-operator-push.yaml".pathChanged()
      || "Dockerfile".pathChanged()
      || "bundle.Dockerfile".pathChanged()
      || "helm-charts/***".pathChanged()
      || "test/***".pathChanged()
      || "go.mod".pathChanged()
      || "go.sum".pathChanged()
      || "Makefile".pathChanged()
      || "config/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: policy-controller-operator
    appstudio.openshift.io/component: policy-controller-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: policy-controller-operator-bundle-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/policy-controller-operator-bundle:{{revision}}
  - name: dockerfile
    value: bundle.Dockerfile
  - name: hermetic
    value: "true"
  - name: build-source-image
    value: "true"
  - name: manager-pipelinerun-selector
    value: appstudio.openshift.io/application=policy-controller-operator,appstudio.openshift.io/component=policy-controller-operator,pipelinesascode.tekton.dev/sha={{revision}},pipelinesascode.tekton.dev/event-type=push
  - name: manager-registry-url
    value: registry.redhat.io/rhtas/policy-controller-rhel9-operator
  - name: release-version
    value: "1.0.0"
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/bundle-build-oci-ta.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-policy-controller-operator-bundle
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
