apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: policycontroller-namespace-lock
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  policyName: policycontroller-namespace-lock
  validationActions: [Deny]
  matchResources:
    namespaceSelector: {}
