apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: policycontroller-namespace-lock
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: ["rhtas.charts.redhat.com"]
      apiVersions: ["v1alpha1"]
      resources: ["policycontrollers"]
      operations: ["CREATE","UPDATE"]
  validations:
  - expression: "request.namespace == 'policy-controller-operator'"
    message: "PolicyController resources may only be created in the policy-controller-operator namespace."
