# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/policy-controller-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard

replacements:
  - source:
      fieldPath: spec.template.spec.containers.[name=manager].image
      kind: Deployment
      name: controller-manager
    targets:
      - fieldPaths:
          - metadata.annotations.containerImage
        select:
          kind: ClusterServiceVersion
