name: Code Coverage

on:
  pull_request:
    branches: [ "main", "release*" ]

jobs:
  coverage:
    name: Upload Code Coverage
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests with coverage
        run: cd cmd && go test -count=1 -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: cmd/coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
