name: Code Coverage

on:
  push:
    branches: [ "main", "release*" ]
  pull_request:
    branches: [ "main", "release*" ]

permissions:
  id-token: write
  contents: read

jobs:
  coverage:
    name: Upload Code Coverage
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests with coverage
        run: cd cmd && go test -count=1 -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: cmd/coverage.out
          use_oidc: true
          flags: unit-tests
          fail_ci_if_error: true

  e2e-coverage:
    name: Upload E2E Coverage
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run E2E tests with coverage
        run: make e2e-test

      - name: Upload E2E coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: e2e-coverage.out
          use_oidc: true
          flags: e2e-tests
          fail_ci_if_error: true
