name: Validate Policy Controller Operator
on:
  workflow_dispatch:
  push:
    branches: [ "main", "release*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main", "release*" ]

permissions:
  id-token: write
  contents: read

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests with coverage
        run: make unit-test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: cmd/coverage.out
          use_oidc: true
          flags: unit
          fail_ci_if_error: true
