name: Validate Policy Controller Operator
on:
  workflow_dispatch:
  push:
    branches: [ "main", "release*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main", "release*" ]

permissions:
  id-token: write
  contents: read

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Run tests with coverage
        run: make unit-test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: cmd/coverage.out
          use_oidc: true
          flags: unit
          fail_ci_if_error: true
